version: '3'
services:
  api.prod.docker:
    container_name: 'api'
    restart: 'always'
    image: api
    user: root
    working_dir: /app/www/
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app/
    expose:
      - 3001
    ports:
      - 3001:3001
    env_file:
      # - /etc/environment
      - docker/api/docker.env
    command: '/./app/docker/api/start.sh'
