version: '3'
services:
  api.dev.docker:
    container_name: 'api'
    image: api
    user: root
    working_dir: /app/www/
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app/
    expose:
      - 3001
    ports:
      - 3001:3001
    env_file:
      - docker/api/docker.env
    command: '/./app/docker/api/start.sh'

  # mysql.dev.docker:
  #   container_name: 'checkout_mysql'
  #   image: checkout_mysql
  #   user: root
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: checkout
  #   volumes:
  #     - ./:/app/
  #   expose:
  #     - 3306
  #   ports:
  #     - 3306:3306
